### ISSUE TITLE
Vargs.Image is an empty string

### ISSUE THREAD

**Issue by normanjoyner** [drone-plugins/drone-containership#8]
In order to fix the plugin whitelist error, I previously [updated our plugin](https://github.com/drone-plugins/drone-containership/commit/6b5eef7e34ade78b9dcdc9a10054e5e6a6863909) to use `docker_image` rather than just `image`.

It appears that `Vargs.Image` is set to an empty string despite the following `.drone.yml` configuration: 

```
deploy:
  containership:
    organization: MyOrg
    api_key: "$$CONTAINERSHIP_API_KEY"
    cluster_id: ContainershipClusterId
    application: myapp
    docker_image: myorg/myapp:$$COMMIT
    when:
      event: push
```

`Vargs.Image` is being set to `{repo_name}:latest` demonstrating it is executing [this line](https://github.com/drone-plugins/drone-containership/blob/master/main.go#L31). Is there something I need to change, or something I need to do to get the plugin changes?
